[package]
name = "my-wasm"
version = "0.1.0"
authors = ["alxs.larionov@gmail.com"]
edition = "2018"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.92"
js-sys = "0.3"
web-sys = { version = "0.3", features = [
  "console",
  "Document", 
  "Window",
  "Performance",
  "HtmlCanvasElement",
  "Cache",
  "Request",
  "Response",
  "CanvasRenderingContext2d",
  "WebGlRenderingContext", 
  "WebGl2RenderingContext", 
  "MouseEvent",
  "WebGlProgram", 
  "WebGlShader", 
  "WebGlBuffer", 
  "WebGlUniformLocation",
  "WebGlVertexArrayObject",
  "WebGlFramebuffer"] }
glam = "0.25.0"
lazy_static = "1.4.0"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
