[package]
name = "my_wasm"
version = "0.1.0"
authors = ["alxs.larionov@gmail.com"]
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = [ ]
web = ["console_error_panic_hook", "wgpu/webgl", "wgpu/webgpu"]

[dependencies]
wasm-bindgen = "0.2.92"
wasm-bindgen-futures = "0.4.42"
wgpu = { version = "0.19.3" }
futures = "0.3.30"
js-sys = "0.3"
bytemuck = { version = "1.15.0", features = [ "derive" ] }
gpp = "0.6.2"
web-sys = { version = "0.3", features = [
    "console",
    "Document",
    "Window",
    "Element",
    "Performance",
    "HtmlCanvasElement",
    "Request",
    "Response",
    "MouseEvent",
    "KeyboardEvent" ] }
glam = "0.25.0"
console_error_panic_hook = { version = "0.1.7", optional = true }

[dev-dependencies]
wasm-bindgen-test = "0.3"
pretty_assertions = "1.4"

[profile.release]
# Tell `rustc` to optimize for small code size.
opt-level = "s"
lto = true
