run-name: "build: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: true
        type: string
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
    outputs:
      build-url:
        value: ${{ jobs.build.outputs.build-url }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      build-url: ${{ steps.upload-artifacts.outputs.artifact-url }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false
        submodules: false

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown

    - run: rustup target add wasm32-unknown-unknown
      continue-on-error: true

    - uses: jetli/wasm-bindgen-action@v0.2.0
      with:
        version: '0.2.92'

    - run: make build_ci
      if: ${{ success() }}
      continue-on-error: true

    - uses: NiklasEi/wasm-opt-action@v2
      id: wasm-opt
      if: ${{ success() }}
      continue-on-error: true
      with:
        file: www/wasm/index_bg.wasm

    - run: make wasm_opt
      if: ${{ failure() && steps.wasm-opt.outcome == 'failure' }}

    - id: upload-artifacts
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: my_web_cv.zip
        path: www
        if-no-files-found: error
        overwrite: false
