run-name: "build: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  workflow_dispatch:
    inputs:
      runs-on:
        required: true
        type: string
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
    outputs:
      build-url:
        value: ${{ jobs.build.outputs.build-url }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      build-url: ${{ steps.upload-artifacts.outputs.artifact-url }}
    env:
      MAX_THREADS: ${{ inputs.runs-on == 'deployee' && 2 || 4 }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false
        submodules: false

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown

    - run: rustup target add wasm32-unknown-unknown

    - run: cargo install wasm-opt --locked --jobs ${{ env.MAX_THREADS }}

    - uses: jetli/wasm-bindgen-action@v0.2.0
      with:
         version: '0.2.92'

    - run: make build_ci
      if: ${{ success() }}

    - id: upload-artifacts
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: my_web_cv.zip
        path: www
        if-no-files-found: error
        overwrite: false
