# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

run-name: "build: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  workflow_call:
    inputs:
      runs_on:
        required: true
        type: string
    outputs:
      build-url:
        value: ${{ jobs.build.outputs.build-url }}
      #build-zip:
      #  value: ${{ jobs.build.outputs.build-zip }}

jobs:
  build:
    runs-on: ${{ inputs.runs_on }}
    outputs:
      build-url: ${{ steps.upload-artifacts.outputs.artifact-url }}
      #build-zip: ${{ steps.zip-artifacts.outputs.build-zip }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false
        submodules: false

    - run: rustup target add wasm32-unknown-unknown

    - uses: jetli/wasm-bindgen-action@v0.2.0

    - run: make build_ci
      if: ${{ success() }}

    - uses: NiklasEi/wasm-opt-action@v2
      if: ${{ success() }}
      with:
        file: www/wasm/index_bg.wasm

    - id: upload-artifacts
      uses: actions/upload-artifact@v4
      if: ${{ success() }}
      with:
        name: my_web_cv.zip
        path: www
        if-no-files-found: error
        overwrite: false
