run-name: "build: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  workflow_dispatch:
    
    inputs:
      runs-on:
        required: true
        type: string
      optimize-wasm:
        default: true
        type: boolean
  workflow_call:
    inputs:
      runs-on:
        required: true
        type: string
      optimize-wasm:
        default: true
        type: boolean
    outputs:
      build-url:
        value: ${{ jobs.build.outputs.build-url }}

jobs:
  build:
    runs-on: ${{ inputs.runs-on }}
    outputs:
      build-url: ${{ steps.upload-artifacts.outputs.artifact-url }}
    env:
      MAX_THREADS: ${{ inputs.runs-on == 'deployee' && 2 || 4 }}
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false
        submodules: false

    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: wasm32-unknown-unknown

    - run: rustup target add wasm32-unknown-unknown

    - uses: jetli/wasm-bindgen-action@v0.2.0
      with:
         version: '0.2.92'

    - id: build
      run: make build_ci
      if: ${{ success() }}

    - run: |
        cargo install wasm-opt --locked --jobs ${{ env.MAX_THREADS }}
        make wasm_opt
      if: ${{ success() && inputs.optimize-wasm }}
      timeout-minutes: 15
      continue-on-error: true

    # since `download-artifacts` loses symbolic links if artifacts are uploaded as raw files
    # I zip the artifacts, so that `download-artifacts` double zips them
    - id: zip-artifacts
      working-directory: ./www
      run: zip -y -r ../my_web_cv.zip .

    - id: upload-artifacts
      uses: actions/upload-artifact@v4
      if: ${{ always() && steps.build.outcome == 'success' }}
      with:
        name: my_web_cv.zip
        path: my_web_cv.zip
        if-no-files-found: error
        overwrite: false
