# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

run-name: "build: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false
        submodules: false
    - name: use-nodejs-${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        always-auth: false # optional, default is false
        node-version: ${{ matrix.node-version }}
        node-version-file: www/package.json # optional
        # architecture: # optional
        check-latest: false # optional
        # registry-url: # optional
        # scope: # optional
        # token: # optional, default is ${{ github.server_url == 'https://github.com' && github.token || '' }}
        cache: 'npm' # optional
        cache-dependency-path: www/package-lock.json # optional

    - name: use-wasm-pack
      uses: jetli/wasm-pack-action@v0.4.0

    - name: build-wasm
      run: wasm-pack build -d build/wasm

    - name: build-npm
      run: |
        npm ci
        npm install
        npm run build --if-present
      working-directory: www

    - name: test-npm
      run: npm test
      working-directory: www
      continue-on-error: true

    - name: start-npm
      run: |
        npm run start
        npx wait-on http://localhost:3000
      working-directory: www
      timeout-minutes: 5
      continue-on-error: true
