# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

run-name: "build: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: false
        submodules: false
    - name: use-wasm-bindgen
      uses: jetli/wasm-bindgen-action@v0.2.0

    - name: use-wasm-opt
      uses: NiklasEi/wasm-opt-action@v2
      with:
        optimize_all: true

    - name: build
      run: make build

    - name: try-serve
      run: make server_py
      timeout-minutes: 1
      continue-on-error: true
