run-name: "deploy: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
jobs:
  build:
    uses: ./.github/workflows/build.yaml

  deploy_cross:
    needs: build
    runs-on: ubuntu-latest
    # [self-hosted]
    steps:
    - name: Install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts

    - name: Download artifacts
      uses: actions/download-artifact@master
      with:
        name: my_web_cv.zip
        path: tmp

    - name: Zip artifacts
      id: zip-artifacts
      working-directory: ./tmp
      run: zip -r my_web_cv.zip .

    - name: Deploy artifacts
      run: |
        scp tmp/my_web_cv.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ vars.WORK_DIR }}
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ vars.WORK_DIR }} && unzip -o my_web_cv.zip -d /var/www/my_web_cv && exit"

    - name: Cleanup
      run: rm -rf ~/.ssh
