run-name: "deploy: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  push:
    branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]
jobs:
  build:
    uses: ./.github/workflows/build.yaml
  deploy_cross:
    runs-on: ubuntu-latest 
    # [self-hosted]
    steps:
    - name: Install ssh keys
      # check this thread to understand why its needed:
      # https://stackoverflow.com/a/70447517
      run: |
        install -m 600 -D /dev/null ~/.ssh/id_rsa
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} > ~/.ssh/known_hosts
    - name: Send build
      run: |
        scp ${{needs.build.outputs.build-zip}} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ secrets.WORK_DIR }}
        ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "cd ${{ secrets.WORK_DIR }} && unzip && exit"
    - name: Cleanup
      run: rm -rf ~/.ssh
