run-name: "deploy: ${{ github.ref_name }} # ${{ github.sha }}"
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      build-runs-on:
        description: 'Runner tag for `build` job'
        default: 'deployer'
        type: string
      deploy-runs-on:
        description: 'Runner tag for `deploy` job'
        default: 'deployee'
        type: string
      optimize-wasm:
        description: 'Build & run WebAssembly optimizer (takes VERY long time to build the optimizer)'
        default: true
        type: boolean
jobs:
  build: # run if `build` failed
    uses: ./.github/workflows/build.yaml
    with:
      runs-on: ${{ inputs.build-runs-on != '' && inputs.build-runs-on || 'deployer' }}
      optimize-wasm: true
  deploy:
    needs: [build]
    secrets: inherit
    uses: ./.github/workflows/deploy.yaml
    with:
      build-run-id: ${{ github.run_id }}
      runs-on: ${{ inputs.deploy-runs-on != '' && inputs.deploy-runs-on || 'deployee' }}
  verify:
    needs: [deploy]
    secrets: inherit
    uses: ./.github/workflows/verify_deploy.yaml
